### ISSUE TITLE
Does not extract inline script blocks

### ISSUE THREAD

**Issue by colinangusmackay** [Soarez/express-ejs-layouts#13]
If I have an `ejs` file with the following in it

    <script src="i-need-a-file.js"></script>
    <script>
        // I'm a script block
    </script>
    <script type="application/javascript" src="i-need-another-file.js"></script>

Then the first and last `script` elements are extracted, but the middle one with inline script remains in place so that now the script blocks are out of sequence when ejs-layout adds the extracts script blocks to the end of page.

The layout is

    <html>
        <body>
            
            <script src="/jquery/jquery-2.1.4.js"></script>
            <script src="/bootstrap4/js/bootstrap.js"></script>

            <%- script %>
       </body>
    </html>

**Comment by Soarez** [comment]
Hello Colin, check the new test. It seems to be working fine.
