### ISSUE TITLE
Empty view file.

### ISSUE THREAD

**Issue by Valonix** [Soarez/express-ejs-layouts#14]
Hello i try to start work with ur extension. 
I create layout and use them in created express app.
There is my layout.ejs
<%- include('partials/header') -%>
<%- include('partials/footer') -%>

This is my route file 
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express',layout: 'layout' });
});

module.exports = router;

I try to write in index.ejs something and don`t see anything, just what i have in header and footer. (ejs files) can u help me and tell what i am doing wrong?
Thank.

**Comment by Soarez** [comment]
Hello Valeriy. You need to specify in the layout where the body goes, i.e. what goes in the index.ejs. So you probably want to have your layout.ejs like this:

```ejs
<%- include('partials/header') -%>
<%- body %>
<%- include('partials/footer') -%>
```

**Comment by Valonix** [comment]
Very tnaks! Now it work. I just want to use MEAN and have 2 layout, one for admin and one for front end. 
I hope i can do this with ur extension :)
