### ISSUE TITLE
Flash messages not showing up

### ISSUE THREAD

**Issue by s2t2** [Soarez/express-ejs-layouts#17]
Hi, as a rails developer, I totally appreciate this library. I did notice something weird though - when I configured my application to use a layout, my flash messages stopped working. I'm using [`express-messages`](https://github.com/expressjs/express-messages).

My layout `app/views/layouts/application.ejs`:

``` html
<!DOCTYPE html>
<html>
  <% include ../_head %>
  <body>
    <% include ../_header %>

    <%- body %>

    <% include ../_footer %>
  </body>
</html>
```

Header partial `app/views/_header.ejs`:

``` html
<header>
  <!-- FLASH MESSAGES -->
  <%- messages('_bootstrap_flash_messages') %>

  <!-- SITE TITLE AND NAVIGATION -->
  <h1><a href="/"><%= title %></a></h1>
  <a type="button" class="btn btn-primary pull-right" href="/robots/new">
    <span class="glyphicon glyphicon-plus"></span> new
  </a>
</header>

<h2><%= page_title %></h2>
```

Bootstrap flash messages partial `app/views/_bootstrap_flash_messages.ejs`:

``` html
<% if(messages){ %>
  <% Object.keys(messages).forEach(function (type) { %>
    <% messages[type].forEach(function (message) { %>
      <div class="alert alert-<%= type %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% }) %>
  <% }) %>
<% } %>

<div>
  TEST TEST TEST
</div>
```

Because I'm seeing the content of the `header` partial but not the text _TEST TEST TEST_, I think the header partial's `<%- messages('_bootstrap_flash_messages') %>` function isn't getting invoked but I'm not sure why. Any guidance you can provide is appreciated.

EDIT: even though an attempt to use a custom flash message template, `<%- messages('_bootstrap_flash_messages') %>`, does not work... an attempt to use the default flash message template,`<%- messages() %>`, does.

**Comment by s2t2** [comment]
Moreover, when I move the contents of the `header` partial and the `bootstrap_flash_messages` partial into the main layout, the messages still don't show up. So the issue goes beyond a failed function invocation.

**Comment by nahwinrajan** [comment]
@s2t2 you are creating a circular reference ...
