### ISSUE TITLE
res.locals not rendering in the layout

### ISSUE THREAD

**Issue by jonnyhaynes** [Soarez/express-ejs-layouts#19]
I'm using the this module with Express 4.

I'm not sure how to label this, but the issue I have is this. I have a routes file, a layout and a view. I'm trying to pass through a *page title* and a *page description* through to the layout using the code below. 

**Route**

    router.get('/', function(req, res, next) {
    
      res.locals.meta = {
        title: 'Page Title',
        description: 'Page Description'
      };
    
      res.render('pages/index', {
        header: 'Page Header'
      });
    });

**Layout**

    <!DOCTYPE html>
    <html dir="ltr" lang="en" class="no-js">
    <head>
      <title><%= meta.title %></title>
      <meta name="description" content="<%= meta.description %>">
    </head>
    <body>
      <%- body %>
    </body>
    </html>

**View**

    <h1 class="page-title"><%= header %></h1>

 
The **header** is rendered in the view, but it's missing the **page title** and **page description**. If I add other items to the `res.locals.meta` object and reference them in the view they're rendered, but nothing from the layout is rendered.

What am I doing wrong?

All help is greatly appreciated.

**Comment by Soarez** [comment]
Unfortunately `meta` was [always being set](https://github.com/Soarez/express-ejs-layouts/blob/ec94fa536725e77518b92087a997efb74a239852/lib/express-layouts.js#L102) regardless of setting `extractMetas`.

Published a new version `2.2.0` with the fix.

**Comment by jonnyhaynes** [comment]
@Soarez thanks for the prompt fix.
