### ISSUE TITLE
difficult to understand manual.

### ISSUE THREAD

**Issue by longxianlin** [Soarez/express-ejs-layouts#24]
not simple libaries

**Comment by manasir** [comment]
I agree manual is difficult to understand. Let me explain more
In `package.json` add 
  `"express-ejs-layouts": "^2.2.0"`

In `app.js` add 
'var ejsLayouts = require("express-ejs-layouts");
app.set('layout', 'layout');   /// or app.set('layout', 'your-layout') , should be an ejs file
app.use(ejsLayouts);`


In views directory create a file `layout.ejs` which should have something like this where you want to show the content 
'''< div class="container body-content">
        <%-body%>
    < /div >'''
That '<%-body%>' will be replaced by the actual content of the file that you router will call.

Create another file , lets say 'content.ejs" with something like this
'< h2><%=hello%>< /h2>'

In the controller , code something like this
'res.render('content', {  hello: "Hello World",}'

this will show your content in the layout file. something like this
< div class="container body-content">
'< h2>Hello World < /h2>
    < /div >

**Comment by Soarez** [comment]
Added [a working example](https://github.com/Soarez/express-ejs-layouts/tree/master/example).
