### ISSUE TITLE
Why a contentFor doesn't have a closeTag?

### ISSUE THREAD

**Issue by djalmaaraujo** [Soarez/express-ejs-layouts#25]
I am trying to understand why a contentFor doesn't have a closeTag? This is so wierd.. I need to open another contentFor to close the past content.

Is that a way to start a contentFor and close after a few lines?

**Comment by Soarez** [comment]
I'm sorry that you find the syntax to be weird.

`contentFor` will consider everything afterwards until the next `contentFor` or the end of the document.

------

> Is that a way to start a contentFor and close after a few lines?

This depends on what you want the lines after that to do.
If you want to define another section, then just use another `contentFor`.
If you don't want to define another content section, then just leave the rest of the document blank.
If you to define custom content _inside_ (or in the middle of) the  special content `body`, then no, that is not possible, and I'm failing to see a good reason to do it.

-------

Here's a helpful way to see this: 
**Think of `contentFor` as headings in a text document, you don't explicitly close them, you just define new sections with new headings.**
