### ISSUE TITLE
How to avoid using a layout for a template?

### ISSUE THREAD

**Issue by chesstrian** [Soarez/express-ejs-layouts#28]
Hi, thanks for this great library, all templates are using the default layout, but I need one of my templates stop using it, how can I do that?.

Thanks in advance.

**Comment by chesstrian** [comment]
Got it from tests:
```js
{ layout: false }
```

**Comment by alexandrucancescu** [comment]
The documentation is really lacking

**Comment by oneEyedSunday** [comment]
Hey @chesstrian I'm having issues getting this library working. It keeps saying it can't find a layout file in views. Any help?

**Comment by oneEyedSunday** [comment]
This is a repo detailing my challenge https://github.com/oneEyedSunday/google-dev-summit-2016-site-clone thanks

**Comment by chesstrian** [comment]
Hey @oneEyedSunday, looks like you are missing the base layout, create a file called `layout.ejs`.
