### ISSUE TITLE
extractScripts and extractStyles don't work as expected

### ISSUE THREAD

**Issue by manu-silicon** [Soarez/express-ejs-layouts#29]
I cloned the repo, did npm install at the root and then launched the server as `node example/index.js`. When I inspect the source of the rendered page in the browser, both style and scripts are still at their original position in the view instead of being respectively at the top and bottom.

Is this expected?

**Comment by Soarez** [comment]
No, it's not expected. But I also can't reproduce this issue.

The [script block](https://github.com/Soarez/express-ejs-layouts/blob/a2817d8865816ea6989928d59361d6ccb39b2c55/example/views/view.ejs#L32-L34) is placed at the end of the rendered HTML and the [style block](https://github.com/Soarez/express-ejs-layouts/blob/a2817d8865816ea6989928d59361d6ccb39b2c55/example/views/view.ejs#L24-L26) is yanked up inside the `<head>` element, as seen below:

```
$ curl http://localhost:3000/
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Example</title>

  
  <style>
  .page-message { color: blue }
</style>
</head>
<body>
  <header>
    
    <h1 class="page-title">Example</h1>

  </header>

  
This is part of the body.








<h1 class="page-message">This is a message</h1>



  <footer>
    
    <h1>This is the footer</h1>


  </footer>

  
  <script>
  // Script content!
</script>
</body>
</html>
```

**Comment by manu-silicon** [comment]
It is definitely not doing it for me. Can you give me directions at where I should be looking at?
I'm getting:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Example</title>

  
  
</head>
<body>
  <header>
    
    
<h1 class="page-title">Example</h1>


  </header>

  

This is part of the body.



<style>
  .page-message { color: blue }
</style>


<script>
  // Script content!
</script>

<h1 class="page-message">This is a message</h1>



  <footer>
    
    
<h1>This is the footer</h1>



  </footer>

  
  
</body>
</html>
```

**Comment by manu-silicon** [comment]
I'm testing on Windows with node.js version 6.10.1

**Comment by manu-silicon** [comment]
I checked and the regular expression for the script extraction doesn't work.

**Comment by Soarez** [comment]
This is really strange, I'm on macOS, tested with the same version of Node, but still can't replicate. Will try with a VM as soon as possible.

**Comment by manu-silicon** [comment]
How do you run the test? `make test` won't do it for me as there is no makefile.


________________________________

**Comment by Soarez** [comment]
Sorry, the instructions were outdated. Run the tests with `npm test`.

**Comment by Soarez** [comment]
#30 might make it work. The test suite fails on windows because of the different EOL used by windows. Until the test suite is fixed, I recommend configuring git and your editor to use linux style line endings i.e. `\n` instead of `\r\n`.

**Comment by manu-silicon** [comment]
Will do. Thanks!
