### ISSUE TITLE
[question]:  using ejs for the layout in an Angular app

### ISSUE THREAD

**Issue by jrmcdona** [Soarez/express-ejs-layouts#33]
I have an Angular project.  I am trying to use ejs just for the layout of the Angular project.  This is because I want to serve dynamic scripts and link tags from express server to the <head> section.

That is all I need it for and after that I am good with the HTML and Angular views.

Your project doesn't by chance help me here does it?   It looks like this is still an all ejs repo.

I am struggling to mix ejs with Angular!   Thanks

**Comment by Soarez** [comment]
Sorry Jordan. I don't know the first thing about Angular. Can't help you with this.

It seems there's [a number of open repositories](https://github.com/search?utf8=✓&q=express-ejs-layouts+angular&type=Code) projects using both express-ejs-layouts and angular that might be helpful.
