### ISSUE TITLE
how to change the delimiter?

### ISSUE THREAD

**Issue by harpreetsb** [soarez/express-ejs-layouts#37]
I would really like to update the delimiter to `?`
how do I do that.

Thank you

**Comment by soarez** [comment]
Hi Harpreet. Sorry, I don't understand your question. What delimiter are you referring to? Please describe the change and purpose.

**Comment by harpreetsb** [comment]
Instead of `<% user %>`
I would like to use
`<? user ?>`

**Comment by soarez** [comment]
Ok. Can you tell us why you need/want this?

**Comment by harpreetsb** [comment]
It is  a Faster key combo

**Comment by soarez** [comment]
Harpreet, please upgrade to 2.5.0 where support for custom delimiters is ensured.

Refer to [`test/view-options.js`](https://github.com/soarez/express-ejs-layouts/blob/8ac3d32446d46441c8ce20590732ad49a863137d/test/view-options.js) for how to configure `?` as a custom delimiter. The bit that matters is: `app.set('view options', { delimiter: '?' })`.

**Comment by bugraaydin1** [comment]
app.set("view options", {
  openDelimiter: "{",
  delimiter: " ",
  closeDelimiter: "}",
});

**Comment by WyndXP** [comment]
The newest release is:
```js
app.set("view options", {
    tags: ["{{", "}}"]
});
```
for use like:
```html
<h1>{{= it.variable }}</h1>
```
