### ISSUE TITLE
Pass variables to layout

### ISSUE THREAD

**Issue by lwf804** [soarez/express-ejs-layouts#39]
Hi, I read code example. And I found the way to pass variables to layout:

```
res.locals = {
    title: 'Example',
    message: 'This is a message'
  };
```

It seem lost old res.locals variables. But I can resolve it by:

```
let locals = res.locals;
res.locals = {
    ...locals
    title: 'Example',
    message: 'This is a message'
  };
```

But It looks pretty complicated. So, can pass variables to layout by ` res.render('views', {variables})`?;

**Comment by soarez** [comment]
That's correct. Alternatively, you can use [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign):

```javascript
res.render(Object.assign({}, res.locals, {
    title: 'Example',
    message: 'This is a message'
})
```
