### ISSUE TITLE
contentFor is not defined in a partials

### ISSUE THREAD

**Issue by kaleidawave** [soarez/express-ejs-layouts#42]
As the title says `contentFor` does not work in partials. Works everywhere else but get `contentFor is not defined` error message when trying to render a page with a partial containing it.

**Comment by soarez** [comment]
Can you provide a concrete example?

**Comment by kaleidawave** [comment]
In `layout.ejs`:
```html
<body>
    <%- include partials/header.ejs %>
    <div id="app">
        <%- body %>
    </div>
    
    <%- defineContent("content") %>
</body>
```

In `partials/header.ejs`:
```html
<header>
    <h1>...</h1>
</header>

<%- contentFor("content") %>
<script>
     ...
</script>
```

And then rendering anything through that layout throws an error. I am now realising that it may be a feature request rather than a bug as only views can use `contentFor` but it would be good if we could use `contentFor` in a partial in a layout rather than a view for development reasons.

**Comment by soarez** [comment]
Thanks for explaining it @kaleidawave.

I think partials should be self contained, and that is somewhat broken by this example where you want a partial view to define content for another section in the template which includes it.
I'm not sure I want to support this use case. It makes things messy.

Why not define another partial instead?
