### ISSUE TITLE
Missing information on the documentation

### ISSUE THREAD

**Issue by ezsystemspt** [soarez/express-ejs-layouts#43]
I had to check the source code to find out that if you pass `false` to the `layout` parameter, you can render the template without using the layout. I would suggest to put it on the README.md as well.

Usage Example:
```
// Not Found (404)
app.use(function(req, res) {
  res.status(404).render('error-404', { layout: false }); // Don't use any layouts for 404 error pages
});
```

**Comment by soarez** [comment]
Sounds good to me. Care to open a PR?
