### ISSUE TITLE
Passing Variables to layout

### ISSUE THREAD

**Issue by JStyle21** [soarez/express-ejs-layouts#46]
Hi,

I'm looking for a way to pass variables to layout, i thought it would work with a regular render i.e.

app.js
`
res.render('view', {
name: value
});
`
layout.ejs
`
<%= name %>
`

But it says it's undefined

Technically it passed through layout but calls a view as the body so does that mean that the variables only pass to the actual view or does layout work in a different way?

**Comment by VirtualWolf** [comment]
I've been wondering the same thing myself. Use-case here is rendering [open graph](https://ogp.me) tags which are dynamically generated on each page, and which need to go into `<head>`.

**Comment by soarez** [comment]
There is at least [one test](https://github.com/soarez/express-ejs-layouts/blob/master/test/simple.js#L43-L53) that covers this. Is it not passing for you?

**Comment by JStyle21** [comment]
@soarez Sorry it was my bad, i was using passport for Auth and forgot about the redirection part of that function, going to another path without those variables was the issue for me.

**Comment by VirtualWolf** [comment]
Yep, I'm a dingus. @soarez Thanks for pointing to the test, that helped. :) I'm not even sure what I was doing last night, but everything works now. 🎉
